[master]
47.128.229.11 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
13.250.20.44 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
13.212.19.160 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
