[master]
18.141.176.224 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
52.77.223.187 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
3.0.91.149 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[jenkins_azure]
20.212.118.76 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa

[sonarqube_azure]
20.212.199.94 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
