---
- name: Prepare all nodes
  hosts: all
  become: yes
  tasks:
    - name: Disable Swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
        
    - name: Load kernel modules for K8s
      shell: |
        modprobe overlay
        modprobe br_netfilter
        cat <<EOF | tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

    - name: Configure sysctl for K8s networking
      shell: |
        cat <<EOF | tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF
        sysctl --system

    - name: Install Containerd and K8s dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, gpg, containerd]
        state: present
        update_cache: yes

    - name: Configure Containerd for Systemd
      shell: |
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml >/dev/null
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        systemctl restart containerd

    - name: Add Kubernetes GPG key and Repository
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install K8s tools
      apt:
        name: [kubelet, kubeadm, kubectl]
        state: present
        update_cache: yes

- name: Initialize Master Node
  hosts: master
  become: yes
  tasks:
    - name: Kubeadm Init
      command: kubeadm init --pod-network-cidr=192.168.0.0/16
      register: init_output
      ignore_errors: yes

    - name: Setup kubectl for ubuntu user
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config

    - name: Get Join Command
      command: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command Fact
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"
        
    - name: Install Calico Network Plugin
      become: false # Run as ubuntu user, not root, to use ~/.kube/config
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml

- name: Join Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Join Workers to Cluster
      shell: "{{ hostvars[groups['master'][0]]['join_command'] }}"
      ignore_errors: yes
